# Time Series {#ts}

## Example

```{r}
plot(globtempl, main = "Global mean land (only) temperature deviations")
```

Perhaps we can just use simple linear regression.


```{r}
data = data.frame(y = as.numeric(globtempl), x = as.numeric(time(globtempl)) )


m0 = lm(y ~ x, data = data)
betas = coefficients(m0)

#summary(m0)


with(data, plot(x, y))
abline(betas[1], betas[2])

```

```{r}
plot(y = residuals(m0), x = as.numeric(time(globtempl)),
     main = "Residuals of Simple Linear Regression")
```


```{r}
acf(residuals(m0))
```


```{r}
#lag1.plot(x,1) # Plots x versus lag 1 of x.
x = as.numeric(globtempl)
acf(x, xlim=c(1,19)) # Plots the ACF of x for lags 1 to 19
xlag1=lag(x,1) # Creates a lag 1 of x variable. See note 2
y=cbind(x,xlag1) # See note 3 below
ar1fit=lm(y[,1]~y[,2])#Does regression, stores results object named ar1fit
summary(ar1fit) # This lists the regression results
plot(ar1fit$fit,ar1fit$residuals) #plot of residuals versus fits
acf(ar1fit$residuals, xlim=c(1,18)) # ACF of the residuals for lags 1 to 18 
```



